package com.topview.www.demo.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-25T12:40:41.143+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://impl.demo.www.topview.com/", name = "HelloWorldImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://impl.demo.www.topview.com/", className = "com.topview.www.demo.impl.GetRoleByUser")
    @WebMethod
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://impl.demo.www.topview.com/", className = "com.topview.www.demo.impl.GetRoleByUserResponse")
    public java.util.List<com.topview.www.demo.impl.Role> getRoleByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.topview.www.demo.impl.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRole", targetNamespace = "http://impl.demo.www.topview.com/", className = "com.topview.www.demo.impl.GetRole")
    @WebMethod
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://impl.demo.www.topview.com/", className = "com.topview.www.demo.impl.GetRoleResponse")
    public com.topview.www.demo.impl.MyRoleArray getRole();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://impl.demo.www.topview.com/", className = "com.topview.www.demo.impl.Say")
    @WebMethod
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://impl.demo.www.topview.com/", className = "com.topview.www.demo.impl.SayResponse")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
